In [12]:
import numpy as np
calls=np.array([5,6,7,8])
print(calls)

[5 6 7 8]


In [18]:
dimensional=np.array ( (['jan','feb','mar'],
                       [300,400,500],
                       [600,700,800]))
print(dimensional.shape)
print(dimensional)

(3, 3)
[['jan' 'feb' 'mar']
 ['300' '400' '500']
 ['600' '700' '800']]


In [37]:
mc=np.array ( (['jan','feb','mar'],
                       [300,400,500],
                       [600,700,800]))
mc[1,1]

np.str_('400')

In [ ]:
sr=np.array([2,3,4,5,6,7])
sr[sr>3]

array([4, 5, 6, 7])

In [ ]:
sr=np.array([2,3,4,5,6,7])
sr[(sr>2) & (sr<4)]

array([3])

In [70]:
dimensional=np.array ((
    
                       [300,400,500],
                       [600,700,800]))
print(np.sum(dimensional[0:].astype(int)))




3300


In [76]:
north = np.array([25,50,75])
south = np.array([100,125,150])
print(np.concatenate((north,south)))


[ 25  50  75 100 125 150]
